export const CREATE_BIKE_REQUEST = 'CREATE_BIKE_REQUEST';
export const CREATE_BIKE_SUCCESS = 'CREATE_BIKE_SUCCESS';
export const CREATE_BIKE_FAIL = 'CREATE_BIKE_FAIL';
export const LIST_BIKE_REQUEST = 'LIST_BIKE_REQUEST'
export const LIST_BIKE_SUCCESS = 'LIST_BIKE_SUCCESS'
export const LIST_BIKE_FAIL = 'LIST_BIKE_FAIL'

