export const CREATE_BIKE_REQUEST = 'CREATE_BIKE_REQUEST';
export const CREATE_BIKE_SUCCESS = 'CREATE_BIKE_SUCCESS';
export const CREATE_BIKE_FAIL = 'CREATE_BIKE_FAIL';
export const CREATE_NEW_BIKE_RESET = 'CREATE_NEW_BIKE_RESET';

export const LIST_BIKE_REQUEST = 'LIST_BIKE_REQUEST';
export const LIST_BIKE_SUCCESS = 'LIST_BIKE_SUCCESS';
export const LIST_BIKE_FAIL = 'LIST_BIKE_FAIL';

export const BIKE_DETAIL_REQUEST = 'BIKE_DETAIL_REQUEST';
export const BIKE_DETAIL_SUCCESS = 'BIKE_DETAIL_SUCCESS';
export const BIKE_DETAIL_FAIL = 'BIKE_DETAIL_FAIL';
