export const CREATE_BIKE_REQUEST = 'CREATE_BIKE_REQUEST';
export const CREATE_BIKE_SUCCESS = 'CREATE_BIKE_SUCCESS';
export const CREATE_BIKE_FAIL = 'CREATE_BIKE_FAIL';
export const CREATE_NEW_BIKE_RESET = 'CREATE_NEW_BIKE_RESET';

export const LIST_BIKE_REQUEST = 'LIST_BIKE_REQUEST';
export const LIST_BIKE_SUCCESS = 'LIST_BIKE_SUCCESS';
export const LIST_BIKE_FAIL = 'LIST_BIKE_FAIL';

export const BIKE_DETAIL_REQUEST = 'BIKE_DETAIL_REQUEST';
export const BIKE_DETAIL_SUCCESS = 'BIKE_DETAIL_SUCCESS';
export const BIKE_DETAIL_FAIL = 'BIKE_DETAIL_FAIL';
export const BIKE_DETAIL_RESET = 'BIKE_DETAIL_RESET';

export const MY_BIKE_REQUEST = 'MY_BIKE_REQUEST';
export const MY_BIKE_SUCCESS = 'MY_BIKE_SUCCESS';
export const MY_BIKE_FAIL = 'MY_BIKE_FAIL';

export const MY_BIKE_UPDATE_REQUEST = 'MY_BIKE_UPDATE_REQUEST';
export const MY_BIKE_UPDATE_SUCCESS = 'MY_BIKE_UPDATE_SUCCESS';
export const MY_BIKE_UPDATE_FAIL = 'MY_BIKE_UPDATE_FAIL';
export const MY_BIKE_UPDATE_RESET = 'MY_BIKE_UPDATE_RESET';

export const MY_BIKE_DELETE_REQUEST = 'MY_BIKE_DELETE_REQUEST';
export const MY_BIKE_DELETE_SUCCESS = 'MY_BIKE_DELETE_SUCCESS';
export const MY_BIKE_DELETE_FAIL = 'MY_BIKE_DELETE_FAIL';

export const BIKE_TOP_REQUEST = 'BIKE_TOP_REQUEST';
export const BIKE_TOP_SUCCESS = 'BIKE_TOP_SUCCESS';
export const BIKE_TOP_FAIL = 'BIKE_TOP_FAIL';

export const BIKE_CREATE_COMMENT_REQUEST = 'BIKE_CREATE_COMMENT_REQUEST';
export const BIKE_CREATE_COMMENT_SUCCESS = 'BIKE_CREATE_COMMENT_SUCCESS';
export const BIKE_CREATE_COMMENT_RESET = 'BIKE_CREATE_COMMENT_RESET';
export const BIKE_CREATE_COMMENT_FAIL = 'BIKE_CREATE_COMMENT_FAIL';
